steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args: ['-c','cd app && mkdir env && gsutil cp gs://${_ENV_BUCKET_NAME}/${_ENV_FILE_NAME} env/prod.env' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: [ '-c', 'cd app && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy' ]
timeout: '1600s'