version: "3"

services:
  #Goのアプリケーション
  app:
    tty: true
    build: ./go
    environment:
      APP_ENV: dev
    volumes:
      - ../app:/go/src/app
    ports:
      - 8080:8080
  #mongoDB
  db:
    image: mongo:4.4.2-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017


volumes:
  mongodb-data:
  gopkg: