version: "3"

services:
  #Goのアプリケーション
  app:
    tty: true
    build: ./go
    environment:
      APP_ENV: dev
    volumes:
      - ../app:/go/src/app
    ports:
      - 8080:8080
  #mongoDB
  db:
    image: mongo:4.4.2-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: